---
- name: Gather facts about the host
  setup:

- name: Ensure config directory exists
  file:
    path: "{{ remote_dir }}/playbooks/monitoring/files/configs"
    state: directory
    mode: '0755'

- name: Copy Docker Compose file
  copy:
    src: docker-compose-client-monitor.yml
    dest: "{{ remote_dir }}/playbooks/monitoring/files/docker-compose-client-monitor.yml"
    mode: '0644'

- name: Copy OTEL collector config
  copy:
    src: configs/otel-collector-config.yaml
    dest: "{{ remote_dir }}/playbooks/monitoring/files/configs/otel-collector-config.yaml"
    mode: '0644'

- name: Replace server_ip in configuration
  replace:
    path: "{{ remote_dir }}/playbooks/monitoring/files/configs/otel-collector-config.yaml"
    regexp: 'server_ip_swap'
    replace: '{{ server_ip }}'

- name: Check Docker installation
  command: which docker
  register: docker_path
  ignore_errors: yes

- name: Start monitoring services
  command: "{{ docker_path.stdout }} compose -f {{ remote_dir }}/playbooks/monitoring