---
- name: Gather facts about the host
  setup:

- name: Replace server_ip in configuration
  replace:
    #path: /home/jenkins/iProlepsisMonitoring/playbooks/monitoring/files/configs/otel-collector-config.yaml
    path: ../configs/otel-collector-config.yaml
    regexp: '{{ server_ip }}'
    replace: '{{ ansible_host }}'
  delegate_to: localhost

#- name: Print the IP address of the current machine
#  debug:
#    msg: "Current IP address: {{ ansible_default_ipv4.address }}"


#- name: Clone monitoring repository
#  git:
    #repo: "https://github.com/iprolepsis-project-eu/monitoring.git"   
#    dest: /opt/monitoring
#if the above cloning works the scp in the jenkinsfile is unecessary, but for now I've removed this

- name: Start monitoring services
  shell: docker compose -f/home/jenkins/iProlepsisMonitoring/playbooks/monitoring/files/docker-compose-client-monitor.yml up -d
  #shell: docker-compose -f/opt/monitoring/playbooks/monitoring/files/docker-compose-client-monitor.yml up -d
  become: yes

- name: Print Monitoring Service Start Success
  debug:
    msg: "Monitoring services started successfully."


#- name: Display Docker Compose configuration
#  command: cat /opt/monitoring/docker-compose.yml


#- name: Ensure Docker service is running
#  service:
#    name: docker
#    state: started
#    enabled: yes
#  become: yes