receivers:
  otlp:
    protocols:
      grpc:
      http:

  prometheus:
    config:
      scrape_configs:
      - job_name: 'main-otel-collector-scraper'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888', '{{ server_ip }}:8081', '{{ server_ip }}:9100']

processors:
  batch:
    timeout: "1s"

extensions:
  health_check:

exporters:
  otlp:
    endpoint: http://5.75.190.25:4317
    tls:
      insecure: true

service:
  pipelines:                                      
    traces:
      receivers: [otlp]
      exporters: [otlp]

    metrics:
      receivers: [prometheus]
      exporters: [otlp]

  extensions: [health_check]