groups:
- name: Server Monitoring
  rules:
    - alert: AlwaysFiring
    expr: vector(1)
    for: 0s
    labels:
      severity: critical
    annotations:
      summary: "This alert is always firing"
      description: "This alert is designed to always be in a firing state for testing"  

