receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
      - job_name: 'main-otel-collector-scraper'
        scrape_interval: 10s
        static_configs:
          - targets: ['0.0.0.0:8888', '161.35.64.89:8080', '161.35.64.89:9100']

processors:
  batch:
    timeout: "1s"

extensions:
  health_check:

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    external_labels:
      label_name1: MainOTELCollector

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]

    metrics:
      receivers: [prometheus, otlp]
      exporters: [prometheusremotewrite]

  extensions: [health_check]
    
