global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collectors'
    scrape_interval: 10s
    static_configs:
      - targets:
        - '209.97.134.226:4317' 
        - '142.93.38.159:4317'  
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'fastapi-apps'
    scrape_interval: 10s
    static_configs:
      - targets:
        - '209.97.134.226:8000'  
        - '142.93.38.159:8000'  
    metrics_path: '/metrics'
    scheme: 'http'

rule_files:
  - /etc/prometheus/alerts.yaml


#Previous version before we had to make this work with fastapi

#global:
#  scrape_interval: 15s
#  evaluation_interval: 15s

#scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']



#rule_files:
#  - /etc/prometheus/alerts.yaml  # Specify the alert rules file