server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://161.35.64.89:3100/loki/api/v1/push

scrape_configs:
  - job_name: system  # Indented one level further
    static_configs:
      - targets: [ localhost ]
        labels:
          hostname: "161.35.64.89"
          job: varlogs
          __path__: /var/log/*log
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: volkovlabs.io
          agent: promtail
          __path__: /var/log/nginx/analytics*log
  #new
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: container_name
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
    # pipeline_stages:
    #   - json:
    #     expressions:
    #       http_user_agent:
    #       request_uri:
    #   - drop:
    #     source: http_user_agent
    #     expression: "(bot|Bot|RSS|Producer|Expanse|spider|crawler|Crawler|Inspect|test)"
    #   - drop:
    #     source: request_uri
    #     expression: "/(assets|img)/"
    #   - drop:
    #     source: request_uri
    #     expression: "/(robots.txt|favicon.ico|index.php)"
    #   - drop:
    #     source: request_uri
    #     expression: "(.php|.xml|.png)$"