- hosts: all
  roles:
    - monitor
---
- hosts: all
  become: yes
  vars:
    server_ip: "{{ lookup('env', 'SERVER_IP') }}"
    friendly_name: "{{ lookup('pipe', 'python get_friendly_name.py ' + server_ip) }}"

  tasks:
    - name: Install required packages
      apt:
        name:
          - git
          - docker
          - docker-compose
          - python3-openpyxl
        state: present
        update_cache: yes

    - name: Copy integration matrix file
      copy:
        src: iPROLEPSIS_IntegrationMatrix.xlsx
        dest: /tmp/iPROLEPSIS_IntegrationMatrix.xlsx

    - name: Clone monitoring repository
      git:
        repo: 'https://github.com/iprolepsis-project-eu/monitoring.git'
        dest: /opt/monitoring
        force: yes

    - name: Copy inventory file
      template:
        src: inventory.j2
        dest: /opt/monitoring/inventory.ini

    - name: Start monitoring stack
      docker_compose:
        project_src: /opt/monitoring
        state: present
        pull: yes
      environment:
        SERVER_IP: "{{ server_ip }}"
        FRIENDLY_NAME: "{{ friendly_name }}"