---
- hosts: localhost
  connection: local
  become: yes
  vars:
    server_ip: "{{ server_ip }}"
    remote_dir: "{{ remote_dir }}"
  
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: yes

    - name: Install Docker if not present
      block:
        - name: Download and install Docker
          shell: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
          args:
            warn: false
          register: docker_install

        - name: Add current user to docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

        - name: Restart Docker service
          systemd:
            name: docker
            state: restarted

      when: docker_check.rc != 0

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Check if Docker Compose plugin is installed
      command: docker compose version
      register: compose_check
      ignore_errors: yes

    - name: Install Docker Compose plugin if not present
      shell: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
      when: compose_check.rc != 0

    - name: Ensure monitoring directory exists
      file:
        path: "{{ remote_dir }}/playbooks/monitoring/files"
        state: directory
        mode: '0755'

  roles:
    - monitoring