---
- hosts: localhost
  connection: local
  become: yes
  vars:
    server_ip: "{{ server_ip }}"
    remote_dir: "{{ remote_dir }}"
    is_monitoring_server: "{{ is_monitoring_server | default(false) }}"
  
  tasks:
    - name: Ensure monitoring directory exists
      file:
        path: "{{ remote_dir }}/playbooks/monitoring/files"
        state: directory
        mode: '0755'

  roles:
    - monitoring