---
- name: List installed packages
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Collect package facts
      ansible.builtin.package_facts:
        manager: "auto"
        strategy: "first"
      register: package_facts_result

    - name: Display package facts
      ansible.builtin.debug:
        var: package_facts_result.ansible_facts.packages

#- hosts: all
#  roles:
#    - monitor


#- hosts: all
#  gather_facts: yes

#  tasks:
 #   - name: Gather user information
 #     shell: |
  #      whoami
   #     id
  #      sudo -l
   #   register: user_info
#
   # - name: Display user information
   #   debug:
   #     var: user_info.stdout_lines

   # - name: Update packages
  #    apt:
    #    name: "*"
  #      state: latest
    #    update_cache: yes
     # become: yes

  









