---
- hosts: all
  become: yes
  roles:
    - monitor
      vars:
        server_ip: "{{ lookup('env', 'SERVER_IP') }}"
        server_name: "{{ lookup('env', 'SERVER_NAME') }}"

#- hosts: all
#  roles:
#    - monitor


#- hosts: all
#  gather_facts: yes

#  tasks:
 #   - name: Gather user information
 #     shell: |
  #      whoami
   #     id
  #      sudo -l
   #   register: user_info
#
   # - name: Display user information
   #   debug:
   #     var: user_info.stdout_lines

   # - name: Update packages
  #    apt:
    #    name: "*"
  #      state: latest
    #    update_cache: yes
     # become: yes

  









